# Generated by Django 4.0.6 on 2022-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=30)),
                ('number', models.IntegerField(max_length=12)),
                ('Release_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('date_of_use', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(null=True)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
