# Generated by Django 4.0.6 on 2022-07-16 21:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Release_date',
        ),
        migrations.AddField(
            model_name='card',
            name='release_date',
            field=models.DateField(default=main.models.expiration_func),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=main.models.expiration_func),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.IntegerField(),
        ),
    ]
