# Generated by Django 4.0.6 on 2022-07-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_card_release_date_card_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card'),
        ),
    ]
